logging:
  level: INFO
  loggers:
    nfReports: DEBUG

server:
  rootPath: /api/*

#dateFormat: yyyy-MM-dd'T'HH:mmZ

#database:
#  driverClass: com.mysql.jdbc.Driver
#  user: root
#  password: 1234
#  url: jdbc:myslq://localhost:3306/nfreports_db

maxLength: 100